name: movies-docker-test
services:
  # movies-db-dumper:
  #   cpus: 5
  #   container_name: movies-db-dumper
  #   image: tiredofit/db-backup:3.9.11
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-db-dumper
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/movies_data
  #       target: /backup_racine
  #       bind:
  #         create_host_path: true
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/movies_data/test
  #       target: /backup
  #       bind:
  #         create_host_path: true
  #   secrets:
  #     - db-pass
  #   env_file: movies-db-dumper.env
  # movies-docusaurus:
  #   cpus: 5
  #   container_name: movies-docusaurus
  #   image: abesesr/movies:develop-documentation
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-docusaurus
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   env_file: movies-docusaurus.env
  # movies-grlc:
  #   cpus: 5
  #   container_name: movies-grlc
  #   image: clariah/grlc:v1.3.8
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-grlc
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   env_file: movies-grlc.env
  # movies-reconciliation:
  #   cpus: 5
  #   container_name: movies-reconciliation
  #   image: registry.gitlab.com/nfdi4culture/ta1-data-enrichment/openrefine-wikibase:1.1.0
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-reconciliation
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/reconciliation/config.sh
  #       target: /openrefine-wikibase/config.sh
  #       bind:
  #         create_host_path: true
  #   env_file: movies-reconciliation.env
  # movies-reconciliation-redis:
  #   cpus: 5
  #   container_name: movies-reconciliation-redis
  #   expose:
  #     - "6379"
  #   image: redis:alpine
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-reconciliation-redis
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  # movies-rp:
  #   cpus: 5
  #   container_name: movies-rp
  #   image: nginx:1.25
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-rp
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   ports:
  #     - mode: ingress
  #       target: 80
  #       published: "12540"
  #       protocol: tcp
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /tmp/docker.sock
  #       read_only: true
  #       bind:
  #         create_host_path: true
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/reverse-proxy/uploadsize.conf
  #       target: /etc/nginx/conf.d/uploadsize.conf
  #       bind:
  #         create_host_path: true
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/reverse-proxy/wikibase.conf.template
  #       target: /etc/nginx/templates/wikibase.conf.template
  #       bind:
  #         create_host_path: true
  #     - type: volume
  #       source: conf
  #       target: /etc/nginx/conf.d
  #       volume: {}
  #     - type: volume
  #       source: certs
  #       target: /etc/nginx/certs
  #       read_only: true
  #       volume: {}
  #     - type: volume
  #       source: vhost-d
  #       target: /etc/nginx/vhost.d
  #       volume: {}
  #     - type: volume
  #       source: html
  #       target: /usr/share/nginx/html
  #       volume: {}
  #     - type: volume
  #       source: dhparam
  #       target: /etc/nginx/dhparam
  #       volume: {}
  #   env_file: movies-rp.env
  movies-wikibase:
    cpus: 5
    container_name: movies-wikibase
    image: abesesr/movies:develop-wikibase
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/processors.add_fields.fields.abes_appli: movies
      co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase
      co.elastic.logs/processors.add_fields.target: ""
    links:
      - movies-wikibase-mysql
    memswap_limit: "5368709120"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/LocalSettings.php
        target: /var/www/html/LocalSettings.d/LocalSettings.override.php
        bind:
          create_host_path: true
      - type: bind
        source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/img/wikibase_logo.png
        target: /var/www/html/img/wikibase_logo.png
        bind:
          create_host_path: true
      - type: bind
        source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/img/favicon.ico
        target: /var/www/html/favicon.ico
        bind:
          create_host_path: true
      - type: bind
        source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/ldap.conf
        target: /etc/ldap/ldap.conf
        bind:
          create_host_path: true
      # - type: volume
      #   source: shared
      #   target: /var/www/html
      #   volume: {}
    secrets:
      - db-pass
      - ldap-pass
      - mw-admin-pass
      - mw-wg-secret-key
    env_file: movies-wikibase.env
  # movies-wikibase-jobrunner:
  #   cpus: 5
  #   container_name: movies-wikibase-jobrunner
  #   image: abesesr/movies:develop-wikibase
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase-jobrunner
  #     co.elastic.logs/processors.add_fields.target: ""
  #   links:
  #     - movies-wikibase-mysql
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/jobrunner-entrypoint.sh
  #       target: /jobrunner-entrypoint.sh
  #       bind:
  #         create_host_path: true
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/LocalSettings.php
  #       target: /var/www/html/LocalSettings.d/LocalSettings.override.php
  #       bind:
  #         create_host_path: true
  #     - type: volume
  #       source: shared
  #       target: /shared
  #       read_only: true
  #       volume: {}
  #   secrets:
  #     - db-pass
  #     - ldap-pass
  #     - mw-admin-pass
  #     - mw-wg-secret-key
  #   env_file: movies-wikibase-jobrunner.env
  movies-wikibase-mysql:
    cpus: 5
    container_name: movies-wikibase-mysql
    image: mariadb:10.9
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/processors.add_fields.fields.abes_appli: movies
      co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase-mysql
      co.elastic.logs/processors.add_fields.target: ""
    memswap_limit: "5368709120"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/volumes/mediawiki-mysql-data
        target: /var/lib/mysql
        bind:
          create_host_path: true
    secrets:
      - mysql-password
      - mysql-random-root-password
    env_file: movies-wikibase-mysql.env
  # movies-wikibase-wdqs:
  #   cpus: 5
  #   container_name: movies-wikibase-wdqs
  #   expose:
  #     - "9999"
  #   image: wikibase/wdqs:0.3.121-wmde.11
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase-wdqs
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/volumes/query-service-data
  #       target: /wdqs/data
  #       bind:
  #         create_host_path: true
  #   env_file: movies-wikibase-wdqs.env
  # movies-wikibase-wdqs-frontend:
  #   cpus: 5
  #   container_name: movies-wikibase-wdqs-frontend
  #   image: wikibase/wdqs-frontend:wmde.11
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase-wdqs-frontend
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   volumes:
  #     - type: bind
  #       source: /home/nblanchet/jeudi_infra/kubernetes/okd/movies-docker-test/wikibase/wdqs_front_index.html
  #       target: /usr/share/nginx/html/index.html
  #       bind:
  #         create_host_path: true
  #   env_file: movies-wikibase-wdqs-frontend.env
  # movies-wikibase-wdqs-proxy:
  #   cpus: 5
  #   container_name: movies-wikibase-wdqs-proxy
  #   image: wikibase/wdqs-proxy:wmde.11
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase-wdqs-proxy
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   secrets:
  #     - proxy-pass-host
  #   env_file: movies-wikibase-wdqs-proxy.env
  # movies-wikibase-wdqs-updater:
  #   cpus: 5
  #   container_name: movies-wikibase-wdqs-updater
  #   image: wikibase/wdqs:0.3.121-wmde.11
  #   labels:
  #     co.elastic.logs/enabled: "true"
  #     co.elastic.logs/processors.add_fields.fields.abes_appli: movies
  #     co.elastic.logs/processors.add_fields.fields.abes_middleware: movies-wikibase-wdqs-updater
  #     co.elastic.logs/processors.add_fields.target: ""
  #   memswap_limit: "5368709120"
  #   restart: unless-stopped
  #   env_file: movies-wikibase-wdqs-updater.env
volumes:
  certs:
    name: movies-docker-test_certs
  conf:
    name: movies-docker-test_conf
  dhparam:
    name: movies-docker-test_dhparam
  html:
    name: movies-docker-test_html
  shared:
    name: movies-docker-test_shared
  vhost-d:
    name: movies-docker-test_vhost.d
secrets:
  db-pass:
    file: db-pass.txt
  ldap-pass:
    file: ldap-pass.txt
  mw-admin-pass:
    file: mw-admin-pass.txt
  mw-wg-secret-key:
    file: mw-wg-secret-key.txt
  mysql-password:
    file: mysql-password.txt
  mysql-random-root-password:
    file: mysql-random-root-password.txt
  proxy-pass-host:
    file: proxy-pass-host.txt
